orange_main:
    resource: "@OrangeMainBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /account/register

#api:
#    type: rest
#    prefix: /api
#    resource: "@OrangeMainBundle/Resources/config/routing_rest.yml"
#
#NelmioApiDocBundle:
#    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
#    prefix:   /api/doc