orange_main:
    resource: "@OrangeMainBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    type: annotation
    prefix: /api
    resource: Orange\MainBundle\Controller\ApplicationController

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /account/register

NelmioApiDoc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
